[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"

replace-with = 'rsproxy-sparse'

[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"

[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"

[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"

#[target.x86_64-unknown-linux-gnu]
#linker = "clang"
#rustflags = ["-C", "link-arg=-fuse-ld=/opt/mold/bin/mold"]

[target.'cfg(target_arch = "wasm32")']
# strip 选项作用如下（详情参考 https://doc.rust-lang.org/cargo/reference/profiles.html#strip）
#   - true 移除辅助调试的符号
#   - debuginfo 指示有选择地移除部分自定义小结的调试信息，例如 .debug_abbrev
rustflags = ["-C", "strip=debuginfo"]
